#!/bin/bash
if [[ -z $1 || $1 == "-h" || $1 == "--help" ]]; then
        echo "Help of openport util"
	echo "Openport is an util that can easily controll firewalld"
        echo "-h - ask for help"
        echo "Examples use:"
        echo "openport [port/tcp or port/udp] - open port"
	echo "openport get ports all - get all ports"
	echo "openport zone public all - get everything about the public zone"
        echo "openport [port1/tcp or port/udp] [port2/tcp or port2/udp] - forward traffic from port 1 to port 2 "
fi

if [[ $3 == "ports" ]]; then
        echo "All opened firewalld ports: "
        sudo firewall-cmd --list-ports
fi

if [[ $3 == "all" ]]; then
	echo "All of "$2" zone: "
	sudo firewall-cmd --zone=$2 --list-all
fi

if [[ $3 == "remove" ]]; then
	echo "Removing port "$4
	sudo firewall-cmd --zone=public --remove-port=$3 --permanent
	sudo firewall-cmd --reload
fi

if [[ -z $3 && -z $2 && -n $1 ]]; then
	echo "Opening port "$1
	sudo firewall-cmd --zone=public --add-port=$1 --permanent
	sudo firewall-cmd --reload
fi

if [[ -z $3 && -n $2 && -n $1 && (( $1 > 0 )) ]]; then
	echo "Redirecting Trafic from port" $1 "to port" $2
	sudo firewall-cmd --zone=public --add-forward-port=port=$1:proto=tcp:toport=$2
	sudo firewall-cmd --reload
fi
